# -------- Build Stage --------
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# -------- Production Stage --------
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
# COPY --from=builder /app/server.js ./server.js
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000

CMD ["npm", "start"]